### ISSUE TITLE
Version 0.90.80 wont start (panic: runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by OccultWarlock** [statping-ng/statping-ng#124]
Hello! I just updated to the newest version and I get this error when attempting to run.

pi@raspberrypi:~ $ statping
INFO[0000] Starting Statping v0.90.80                    type=cmd
INFO[0000] Attempting to read config file at: /home/pi/config.yml  type=configs
INFO[0000] Database mysql connection was successful.     type=configs
INFO[0000] Migrating Database Tables...                  type=configs
INFO[0000] Migrating App to version: 0.90.80 (205ca5aeea88c510577195b97be993be1af0057a)  type=configs
INFO[0000] Statping Database Tables Migrated             type=configs
INFO[0000] Database Indexes Created                      type=configs
INFO[0000] Error Reporting initiated, thank you!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa54e2c]

goroutine 50 [running]:
github.com/statping-ng/statping-ng/types/services.UpdateNotifiers()
        /source/types/services/notifications.go:17 +0x9c
github.com/statping-ng/statping-ng/notifiers.InitNotifiers()
        /source/notifiers/notifiers.go:43 +0x1c4
main.InitApp(0x1d01300, 0x4000179100)
        /source/cmd/main.go:156 +0x4c
main.mainProcess(0x40003961e0, 0x0)
        /source/cmd/main.go:130 +0x20
main.start()
        /source/cmd/main.go:115 +0x308
main.glob..func1(0x2ad7600, 0x2b85108, 0x0, 0x0)
        /source/cmd/commands.go:19 +0x20
github.com/spf13/cobra.(*Command).execute(0x2ad7600, 0x40001182a0, 0x0, 0x0, 0x2ad7600, 0x40001182a0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x1c4
github.com/spf13/cobra.(*Command).ExecuteC(0x2ad7600, 0x467934, 0x40002ee180, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.Execute()
        /source/cmd/commands.go:204 +0x30
created by main.main
        /source/cmd/main.go:67 +0x30

**Comment by vkorn** [comment]
This fixed it for me. Looks like it's related to https://github.com/statping-ng/statping-ng/commit/86ecefcef918b6cf8b782c6790c61b412ad7fcf5

```
delete from notifications where method='statping_emailer'
```
