### ISSUE TITLE
V0.90.80 Docker build fails

### ISSUE THREAD

**Issue by adamboutcher** [statping-ng/statping-ng#125]
Docker build is failing on stable action.

**Comment by adamboutcher** [comment]
FYI I'm still working on this..

This is the error I'm hitting on the docker buildx
`
docker buildx create --name statping-latest --driver-opt image=moby/buildkit:master
error: existing instance for statping-latest but no append mode, specify --node to make changes for existing instances
make: *** [Makefile:364: buildx-latest] Error 1
Error: Process completed with exit code 2.
`

Does @jemand771 or @jonathanrbarney understand this error?
II believe I have a clean build area... :-/

**Comment by jemand771** [comment]
the weird thing isn't why the stable build fails, but why the unstable build worked at all - the command is pretty much the same (but with different tags and a different builder name)

**Comment by jemand771** [comment]
I have an idea why running `make statping-latest` locally doesn't work for you, but I don't get what's failing inside the actions workflow.

can you check the output of `docker buildx ls` ? my current hypothesis is

1. first build: builder gets created
2. build runs and fails
3. (builder doesn't get deleted because the make target gets aborted)
4. second build: try to create builder _again_ -> fails

but as I've said, no idea why actions is failing. it's not like we changed anything significant inside the makefile or dockerfile recently. as a workaround, we _could_ run something like `docker buildx rm statping-latest || true` right before executing `make docker-latest`

**Comment by adamboutcher** [comment]
Apologies, work and covid have go in the way of me progressing with this at the moment. 😔😷☣️

**Comment by joelhoward** [comment]
Any progress on this?  Or abandoned?

**Comment by adamboutcher** [comment]
Not abandoned just I currently dont have lots of spare time.

**Comment by WaiserHai** [comment]
Hi, any progress ?

**Comment by adamboutcher** [comment]
Apologies I haven't got around to this due to health issues and work commitments.

**Comment by WaiserHai** [comment]
all the best

**Comment by zdhamasha** [comment]
@WaiserHai 
you can use 
https://quay.io/repository/statping-ng/statping-ng

**Comment by WaiserHai** [comment]
and how ? its showing me errors. the image is quay.io/statping-ng/statping-ng:latest or? 
 using docker Compose

![grafik](https://user-images.githubusercontent.com/116884597/213160139-1f3f9534-f446-44ee-8dab-24f0a7ae5c66.png)

**Comment by zdhamasha** [comment]
show me your compose or docker run  command  @WaiserHai

**Comment by WaiserHai** [comment]
![grafik](https://user-images.githubusercontent.com/116884597/213161191-44512617-2972-4a17-b9bf-dd7b7286a509.png)

**Comment by zdhamasha** [comment]
please pasted as a text

**Comment by WaiserHai** [comment]
version: '2.3'

services:
  statping:
    container_name: statping
    image: quay.io/statping-ng/statping-ng:v0.90.80
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - '127.0.0.1:8082:8080'

        
volumes:
  statping_data:
        
networks:
  default:
    name: shared-docker-network
    external: true

**Comment by astravexton** [comment]
Just tried this myself but with `podman` and get the same error

```podman run --name statping-ng -p 8889:8080 -v statping:/app quay.io/statping-ng/statping-ng:latest```

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xb47581]

goroutine 14 [running]:
github.com/statping-ng/statping-ng/types/services.UpdateNotifiers()
        /go/src/github.com/statping-ng/statping-ng/types/services/notifications.go:17 +0xa1
github.com/statping-ng/statping-ng/notifiers.InitNotifiers()
        /go/src/github.com/statping-ng/statping-ng/notifiers/notifiers.go:43 +0x1d2
main.InitApp(0x182f460, 0xc0000956c0)
        /go/src/github.com/statping-ng/statping-ng/cmd/main.go:156 +0x59
main.mainProcess(0xc00000c3c0, 0x0)
        /go/src/github.com/statping-ng/statping-ng/cmd/main.go:130 +0x26
main.start()
        /go/src/github.com/statping-ng/statping-ng/cmd/main.go:115 +0x334
main.glob..func1(0x30260c0, 0xc00000f660, 0x0, 0x2)
        /go/src/github.com/statping-ng/statping-ng/cmd/commands.go:19 +0x20
github.com/spf13/cobra.(*Command).execute(0x30260c0, 0xc00003c190, 0x2, 0x2, 0x30260c0, 0xc00003c190)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x30260c0, 0xc0002ec180, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.Execute()
        /go/src/github.com/statping-ng/statping-ng/cmd/commands.go:204 +0x2d
created by main.main
        /go/src/github.com/statping-ng/statping-ng/cmd/main.go:67 +0x35
```

The only notification service I have set up is Telegram, however, if I run it fresh without v0.90.78 config/database it starts fine.

**Comment by Navneet7716** [comment]
any updates on this?

**Comment by N0N4M3BNS** [comment]
any updates on this?

**Comment by jemand771** [comment]
0.91.0 is out (and has been for a while). I assume this makes the build for this older version irrelevant.
we're using the ghcr.io registry for new releases, btw (see "packages" section on the right of this repo's landing page)

as for the other issue mentioned in this thread - please go see if the new version fixes it

**Comment by saschaludwig** [comment]
> 0.91.0 is out (and has been for a while). I assume this makes the build for this older version irrelevant. we're using the ghcr.io registry for new releases, btw (see "packages" section on the right of this repo's landing page)
> 
> as for the other issue mentioned in this thread - please go see if the new version fixes it

Where can one find the latest docker image? Looks like https://hub.docker.com/r/adamboutcher/statping-ng/tags is pretty much dead in the last 3 years. Is there a new repo somewhere?

**Comment by jemand771** [comment]
`ghcr.io/statping-ng/statping-ng:0.92.0` - see https://github.com/statping-ng/statping-ng/pkgs/container/statping-ng (you also get redirected there if you open [ghcr.io/statping-ng/statping-ng](https://ghcr.io/statping-ng/statping-ng) in your browser)

if you're wondering why, the tldr is that ghcr integrates very nicely into github actions and we don't need to manage push secrets for anyone like we would have to on an external registry.

**Comment by saschaludwig** [comment]
Is it possible to get edit rights for the wiki, so I can fix the docker documentation and replace the URLs?

**Comment by jemand771** [comment]
@saschaludwig I don't think I'm comfortable with handing out full wiki access, but you _can_ clone the wiki locally, make your changes and post the diff in a new issue. You can also push your changes to a repo in your own account, I can pull these in manually

[this SO answer](https://stackoverflow.com/a/11481887/9145163) may help you wit hthat
