### ISSUE TITLE
Non admin user login

### ISSUE THREAD

**Issue by MaxHayman** [statping-ng/statping-ng#148]
Hello,

With a non admin user i seem to get an error when logging in to the dashboard

```
api/users/token:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.chunk.js:1 Error: Request failed with status code 500
    at t.exports (vendor.chunk.js:23:46270)
    at t.exports (vendor.chunk.js:48:17769)
    at d.onreadystatechange (vendor.chunk.js:23:45122)
(anonymous) @ main.chunk.js:1
api/checkins:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
vendor.chunk.js:7 Error: Request failed with status code 401
    at t.exports (vendor.chunk.js:23:46270)
    at t.exports (vendor.chunk.js:48:17769)
    at d.onreadystatechange (vendor.chunk.js:23:45122)
```

Changing the user to an admin fixes the issue but I would rather people not have admin permissions to add incident messages

**Comment by adamboutcher** [comment]
We will try and look into this, we suspect its an API permissions thing.

**Comment by MaxHayman** [comment]
Thanks @adamboutcher. That would be fantastic.
