### ISSUE TITLE
notifiers hard crash with traceback

### ISSUE THREAD

**Issue by rinchen** [statping-ng/statping-ng#269]
~ statping -p 9876                                                                                                                        3 [12:01:33]INFO[0000] Starting Statping v0.90.74                    type=cmd
INFO[0000] Attempting to read config file at: /root/config.yml  type=configs
INFO[0000] Database mysql connection was successful.     type=configs
INFO[0000] Migrating Database Tables...                  type=configs
INFO[0000] Migrating App to version: 0.90.74 (2352cae85cb388437ae848c6acd0a658a4cd2d84)  type=configs
INFO[0000] Statping Database Tables Migrated             type=configs
INFO[0000] Database Indexes Created                      type=configs
INFO[0000] Error Reporting initiated, thank you!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xb85da3]

goroutine 8 [running]:
github.com/statping/statping/types/services.UpdateNotifiers()
        /source/types/services/notifications.go:17 +0xa3
github.com/statping/statping/notifiers.InitNotifiers()
        /source/notifiers/notifiers.go:43 +0x1d7
main.InitApp(0x21fde20, 0xc000403580)
        /source/cmd/main.go:156 +0x5b
main.mainProcess(0xc00000c3c0, 0x0)
        /source/cmd/main.go:130 +0x28
main.start()
        /source/cmd/main.go:115 +0x33e
main.glob..func1(0x2fda620, 0xc0002eb480, 0x0, 0x2)
        /source/cmd/commands.go:19 +0x25
github.com/spf13/cobra.(*Command).execute(0x2fda620, 0xc0000aa160, 0x2, 0x2, 0x2fda620, 0xc0000aa160)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2fda620, 0xc00009e0c0, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.Execute()
        /source/cmd/commands.go:204 +0x2f
created by main.main
        /source/cmd/main.go:67 +0x37

**Comment by rinchen** [comment]
Interestingly, I'm on the latest version, not the version listed here.

~ statping update                                                                                                                         2 [12:01:49]
INFO[0000] Updating Statping to the latest version...    type=cmd
INFO[0000] curl -o- -L https://statping.com/install.sh | bash  type=cmd
INFO[0003] Installing Statping!
> Downloading latest version for linux amd64...
https://github.com/statping/statping/releases/latest/download/statping-linux-amd64.tar.gz
> Installing to /usr/local/bin/statping
> Statping is now installed!
>   Repo:     https://github.com/statping/statping
>   Wiki:     https://github.com/statping/statping/wiki
>   Issues:   https://github.com/statping/statping/issues
> Try to run "statping help"   type=cmd

root @ netops in ~ 0 [12:06:03]
~ statping -p 9876                                                                                                                        0 [12:06:03]
INFO[0000] Starting Statping v0.90.74                    type=cmd
INFO[0000] Attempting to read config file at: /root/config.yml  type=configs
INFO[0000] Database mysql connection was successful.     type=configs
INFO[0000] Migrating Database Tables...                  type=configs
INFO[0000] Migrating App to version: 0.90.74 (2352cae85cb388437ae848c6acd0a658a4cd2d84)  type=configs
INFO[0000] Statping Database Tables Migrated             type=configs
INFO[0000] Database Indexes Created                      type=configs
INFO[0000] Error Reporting initiated, thank you!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xb85da3]

**Comment by rinchen** [comment]
Looks like update nor the one-liner install script update statping so I did it manually. Problem remains.

~ statping -p 9876                                                                                                                      130 [12:09:58]
INFO[0000] Starting Statping v0.91.0                     type=cmd
INFO[0000] Attempting to read config file at: /root/config.yml  type=configs
INFO[0000] Database mysql connection was successful.     type=configs
INFO[0000] Migrating Database Tables...                  type=configs
INFO[0000] Migrating App to version: v0.91.0 (66a1adaa66acfa9615d5b8661e3c0320109731c3)  type=configs
INFO[0000] Statping Database Tables Migrated             type=configs
INFO[0000] Database Indexes Created                      type=configs
INFO[0000] Error Reporting initiated, thank you!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x874fb2f]

goroutine 36 [running]:
github.com/statping-ng/statping-ng/types/services.UpdateNotifiers()
        /source/types/services/notifications.go:17 +0x8f
github.com/statping-ng/statping-ng/notifiers.InitNotifiers()
        /source/notifiers/notifiers.go:43 +0x1e6
main.InitApp()
        /source/cmd/main.go:156 +0x56
main.mainProcess()
        /source/cmd/main.go:130 +0x1f
main.start()
        /source/cmd/main.go:115 +0x420
main.glob..func1(0xa6db9e0, {0xb04a540, 0x0, 0x2})
        /source/cmd/commands.go:19 +0x18
github.com/spf13/cobra.(*Command).execute(0xa6db9e0, {0xac3c020, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x698
github.com/spf13/cobra.(*Command).ExecuteC(0xa6db9e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x46a
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.Execute()
        /source/cmd/commands.go:204 +0x2b
created by main.main
        /source/cmd/main.go:67 +0x29

**Comment by rinchen** [comment]
If it would help, I'd be happy to dump my database and share it. It's all internal network systems.

**Comment by rinchen** [comment]
Here is a sanitized version (removed user, removed telegram code) dump of my database. I authorize all the devs to use the information inside for testing. The password to the file is "traceback". The link will expire on 2 March. 

https://e.pcloud.link/publink/show?code=XZONveZHyEtVybJkUzdoC3jDcNhKfpHnavk

**Comment by Navneet7716** [comment]
Hi @adamboutcher, @jemand771, @rinchen,

I’m encountering the same issue and was wondering if you could help out. Also I’ve been trying to set up a development environment—currently, I have a workaround, but it’s a bit hacky. I’d really appreciate guidance on a cleaner and more replicable approach.

Thanks in advance!
