### ISSUE TITLE
Upgrade/migration guide.

### ISSUE THREAD

**Issue by thangaraja** [statping-ng/statping-ng#28]
Is there a guide that explains how to move from statping to statping-ng?

**Comment by jemand771** [comment]
in theory it should be as simple as swapping out the executable or changing the docker image name (depending on how you deployed statping)

in practice.. not all of our builds are stable yet, and we have no AWS integration or homebrew releases. we're still working on a more reliable release automation anyway ^^

**Comment by adamboutcher** [comment]
@thangaraja Have you managed to swap out the binary/container? Let us know if there's anything broken.

**Comment by saschaludwig** [comment]
I'm also unable to migrate, even from statping-ng v0.90.78 to v0.91 or v0.92:

```
INFO[0000] Starting Statping v0.92.0                     type=cmd
INFO[0000] Attempting to read config file at: /app/config.yml  type=configs
INFO[0000] Database postgres connection was successful.  type=configs
INFO[0000] Migrating Database Tables...                  type=configs
INFO[0000] Migrating App to version: v0.92.0 (ad39c6523da055360f71f879a6b8824743484d92)  type=configs
INFO[0000] Statping Database Tables Migrated             type=configs
INFO[0000] Database Indexes Created                      type=configs
INFO[0000] Error Reporting initiated, thank you!        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xaa897c]
goroutine 21 [running]:
github.com/statping-ng/statping-ng/types/services.UpdateNotifiers()
	/go/src/github.com/statping-ng/statping-ng/types/services/notifications.go:17 +0x7c
github.com/statping-ng/statping-ng/notifiers.InitNotifiers()
	/go/src/github.com/statping-ng/statping-ng/notifiers/notifiers.go:43 +0x1ca
main.InitApp()
	/go/src/github.com/statping-ng/statping-ng/cmd/main.go:156 +0x4a
main.mainProcess()
	/go/src/github.com/statping-ng/statping-ng/cmd/main.go:130 +0x1d

main.start()
	/go/src/github.com/statping-ng/statping-ng/cmd/main.go:115 +0x265
main.glob..func1(0x2b1b1e0?, {0x18e6dc7?, 0x2?, 0x2?})
	/go/src/github.com/statping-ng/statping-ng/cmd/commands.go:19 +0x17
github.com/spf13/cobra.(*Command).execute(0x2b1b1e0, {0xc000112160, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2b1b1e0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.Execute()
	/go/src/github.com/statping-ng/statping-ng/cmd/commands.go:204 +0x25
created by main.main
	/go/src/github.com/statping-ng/statping-ng/cmd/main.go:67 +0x25

```

Edit: maybe related to this https://github.com/statping-ng/statping-ng/issues/263

**Comment by saschaludwig** [comment]
As a workaround: you can export your config to a json file, then delete the database and update to the desired version. Once your fresh and empty instance is up again, you can delete all example checks (to avoid primary key errors/duplicate IDs) and import your settings from the json file.
But be aware that you lose all history data, at least that was the case when I tried this.
